name: Tim Robinson (That Voice)
description: You would NOT have liked me very much ğŸ˜µâ€ğŸ’«

1:
  source:
    location: input/1.mp3
    type: file

2:
  source:
    location: input/2.mp3
    type: file
3:
  source:
    location: input/3.mp3
    type: file
4:
  source:
    location: input/4.mp3
    type: file
5:
  source:
    location: input/5.mp3
    type: file
